### PR TITLE
fixed most 3ds resampler issues by fixing up the high-pass code and increased the resampler accuracy

### PR DESCRIPTION
**Pull request by FIX94**
just some changes I made to get the sound of some gb games actually sounding acceptable on 3ds.

### CODE REVIEW

**Comment by twinaphex** [comment]
OK I'll let @aliaspide review this since he wrote the CC resampler.

**Comment by aliaspider** [comment]
"actually sounding acceptable on 3ds." .. what ?!

**Comment by aliaspider** [comment]
ok, I see that you made the highpass use different accumulators for l and r instead of just one, which was indeed wrong, but it didn't seem needed in most tests I've made.
Can you give me the name of a title where these changes make a noticeable improvement?

**Comment by FIX94** [comment]
check out the music in for example mickeys dangerous chase, the jetsons, the smurfs nightmare and robocop, some notes will sound pretty broken.

**Comment by aliaspider** [comment]
ok yeah I see the problem now, the high-pass was overflowing with those games, since they like to shift their bias around like crazy, and I didn't proof test the resampler enough I guess xD.

a simple fix would have been to increase the shift amount from 14 to 15, that does of course come at the cost of reducing the volume, but I think the output level would be the same as the more accurate resampler (blipper.c) that is currently used for most targets.

your highpass does seem to partially solve the overflow problem, but not completely, without reducing the volume, so I'll just merge this for now and see if it can be improved upon later, to completely solve the overflow problem, if not, I'll just revert to the simpler highpass code with an extra shift.

maybe an extra core option to select the resampler would be beneficial here since I think the new 3DS can handle the blipper.c pretty well.

and thanks for cleaning up the intendation :)

**Pull request merged**
