### PR TITLE
Fix cheevos depending on the Zero Page RAM and the Interrupt Enable Flag

### PR DESCRIPTION
**Pull request by leiradel**

### CODE REVIEW

**Comment by Alcaro** [comment]
> const void *zeropage_ptr() const { return ioamhram_ + 0x0180; }

That looks important. Are you sure you only want to expose the last quarter?

>      {   0, gb.vram_ptr(),        0, 0x8000,               0, 0, 0x2000,  NULL },
>      {   0, (void*)zeropage_copy, 0, 0xFF80,               0, 0, 0x0080,  NULL },

The memory descriptors should be sorted by likelihood of being targeted by cheats/etc. Are you sure VRAM is more interesting than the zero page?

> unsigned ff_read(unsigned p, unsigned long cc) { return mem_.ff_read(p, cc); }

I'll have to double check whether that one changes the program state.

**Comment by Alcaro** [comment]
> I'll have to double check whether that one changes the program state.

Hey, you know what?

```
   memcpy((void*)zeropage_copy, zeropage_ptr, 128);
   zeropage_copy[127] = gb.ff_read(0xff, 0);
...
   const void *zeropage_ptr() const { return ioamhram_ + 0x0180; }
...
	unsigned ff_read(unsigned p, unsigned long cc) {
		return p < 0x80 ? nontrivial_ff_read(p, cc) : ioamhram_[p + 0x100];
	}
```

That ff_read thingy is just a fancy way of reading the value you already have.

**Comment by leiradel** [comment]
> That looks important. Are you sure you only want to expose the last quarter?

Yeah, ioamhram_ also holds the Object Attribute Memory. I'll add another method to return a pointer to it, unless you think it's better to expose the full 512 bytes even though there are hardware registers inside that range.

> The memory descriptors should be sorted by likelihood of being targeted by cheats/etc

I never thought about sorting the memory descriptors in that way. In cheevos.c, I save the memory descriptor index during achievement setup, so it won't get any speedup with the sort. I can do it, but I'm not sure which the correct order would be by this criteria.

> That ff_read thingy is just a fancy way of reading the value you already have.

Indeed! I'll test it to make sure.

**Comment by leiradel** [comment]
Yup, we don't need to call `ff_read`, I'll make the changes and commit to this PR. If you want me to change the order of the descriptors, please advise. I'll do it later today or tomorrow, have to leave now.

Thanks!

**Comment by Alcaro** [comment]
> there are hardware registers inside that range

If reading the pointer doesn't return same value as if the game itself does it, it's a hardware register and shouldn't be exposed.

Add a comment and I'm happy. (Gambatte spends way too much effort on merging allocations.)

> I never thought about sorting the memory descriptors in that way.

Cheevos doesn't and shouldn't care about order. (Unless multiple mappings target the same byte, but that's rare.)

But cheat search does. The most likely target for a cheat should be on top.

And as far as I can see, the most likely target is this one.

> Yup, we don't need to call ff_read

Then let's just return the original pointer, so update_zero_page() disappears completely. And so the frontend can write to there.

**Comment by leiradel** [comment]
> And so the frontend can write to there.

I'll have tp remove the constantness of the pointer, but I don't think it'll be a problem.

**Comment by Alcaro** [comment]
> I'll have to remove the constantness of the pointer

Alternative solution: You're adding about eight functions, which return const void*.

Change them to void*.

**Pull request merged**
