### PR TITLE
Default palette is dark green & improve core settings descriptions

### PR DESCRIPTION
**Pull request by sergiobenrocha2**

### CODE REVIEW

**Comment by meepingsnesroms** [comment]
"Special 1" is more accurate than "GBC Dark Green"

**Comment by sergiobenrocha2** [comment]
Default palette using gbc bios:

final fantasy legend ii usa -170216-010330

Dark Green:

final fantasy legend ii usa -170216-010447

Final Fantasy Legend II

**Comment by meepingsnesroms** [comment]
So that is the default for gbc, I thought you meant gb to have the 4 green colors like the real display, sorry.

Then it is perfectly fine, thank you for helping.

**Comment by sergiobenrocha2** [comment]
Yup, it's the default palette when the game is not listed in gbcTitlePalettes[] in gbcpalettes.h (For those who are curious)

**Pull request merged**
