### PR TITLE
Fixed compilation issues in MSVC

### PR DESCRIPTION
**Pull request by albertofustinoni**
Also added proper aspect ratio

### CODE REVIEW

**Comment by twinaphex** [comment]
I ask again, can we put an RT system define around that compat/msvc.h include then instead of overtly removing it? This will cause problems for our other MSVC ports otherwise.

**Comment by albertofustinoni** [comment]
I didn't see your first comment about this, my apologies.

I will 
definitely add the define: should it be an exclude if building in Visual Studio? Not sure what that file is supposed to do, since it's not present.

**Comment by twinaphex** [comment]
OK, I get what is going on then.

**Comment by twinaphex** [comment]
Check if this resolves your issue instead -

https://github.com/libretro/gambatte-libretro/commit/0caab0ef13d3b7c622d3228f79fa47d63b4a5a73

**Comment by albertofustinoni** [comment]
@twinaphex Thanks for your change: it does indeed solve the issue with the header.

Are you OK with the other changes?

**Comment by twinaphex** [comment]
The rest seems fine yeah.

**Pull request merged**
