### PR TITLE
Improve the Makefiles

### PR DESCRIPTION
**Pull request by bochecha**
Most projects have a Makefile (whether static or generated by something like the autotools or cmake) in the root directory. This pull request moves the `Makefile*` files to the root directory, to be a bit less surprising.

In addition, this adds the `install` and `uninstall` rules, to make the Makefile even more useful.

### CODE REVIEW

**Comment by Alcaro** [comment]
Haven't those .T been redundant since [17 months ago](https://github.com/libretro/libretro-arb/commit/8adf46cc529e6371724fd2c01c9acc7449ccddf1)? Surprised they're still around.

Either way, looks good to me, except we don't want to add toplevel files I'm not sure if we're trying to remain as close to upstream as possible. I'll leave that question for the local maintainer.

**Comment by bochecha** [comment]
> Haven't those .T been redundant since 17 months ago? Surprised they're still around.

No idea, really, I just moved things around, trying to break as few as possible in the process.

> I'm not sure if we're trying to remain as close to upstream as possible

Seems like this repo has already diverged a lot from upstream.

First of all, they are hard to compare, because they don't have any history (commits hashes) in common.

Doing a bit of spelunking, it seems the last common commit between upstream and the libretro fork is this one:

```
Author: sinamas <sinamas@users.sourceforge.net>
Date:   Sat Sep 24 19:54:17 2011 +0000

    libgambatte: compilation and warning fixes for clang.
    
    
    git-svn-id: https://gambatte.svn.sourceforge.net/svnroot/gambatte@276 9dfb2916-2d38-0410-aef4-c5fe6c9ffc24
```

In the upstream Git repository that's commit hash 41952f42f41702f8efb7d40c72cbf8baa6aa9a7f, and in the libretro fork it is commit 226b539d9c8da56c555efb138971e6d0579e6b67.

(Looking at the commit message, I would guess that the reason why there is no common ancestry between the two is that the people who forked it for libretro did a svn to git conversion, then later on when upstream moved to Git they also did a similar conversion, but that gave them different commit hashes)

So it seems the two have diverged some 5 years ago.

That doesn't necessarily mean that it's ok to diverge them even more with my change, of course, maybe the answer is to try and rebase the libretro changes on top of the latest upstream, to get back closer to them? :smiley:

**Comment by bochecha** [comment]
So, here's a compromise offer: would you take a pull request that only adds the `install` and `uninstall` targets to the `Makefile.libretro`, without moving it?

This is really all I actually care about.

The moving was more out of habit, but I can understand you're hesitant to diverge too much from upstream (although it seems that ship has sailed a long time ago).

If that works for you, I'll force push to this branch.

**Comment by Alcaro** [comment]
I don't actually know if we do want to follow upstream. Some of our repos do, some don't, and if this one is in the latter category, I fully agree with moving the makefiles.

@twinaphex, you know the non-SNES repos better than I do. Is this repo a shallow fork? And do cores need make install targets?

**Comment by twinaphex** [comment]
We are more recent than upstream at this point. Guess I'll just merge it.

**Comment by bochecha** [comment]
Thanks!

**Pull request merged**
